version: '3'
services:
  database:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: cryptobazar
      POSTGRES_PASSWORD: KAUSihdauiskdhiaukw324234ASd13d31d3w2raASdawd
      POSTGRES_DB: bazar
    ports:
      - '7432:5432'

  backend:
    volumes:
      - ./src:/app/src
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/bazar
      SPRING_DATASOURCE_USERNAME: cryptobazar
      SPRING_DATASOURCE_PASSWORD: KAUSihdauiskdhiaukw324234ASd13d31d3w2raASdawd
    depends_on:
      - database
    ports:
      - '8080:8080'