version: '3'
services:
  database:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: cryptobazar
      POSTGRES_PASSWORD: KAUSihdauiskdhiaukw324234ASd13d31d3w2raASdawd
      POSTGRES_DB: bazar
    ports:
      - '7432:5432'